[15-06-2025 23:30:39] 12 root - INFO - Logging is working from app.py!
[15-06-2025 23:30:39] 26 root - INFO - reading from Mysql database
[15-06-2025 23:30:39] 23 root - INFO - Reading data from MySQL database
[15-06-2025 23:30:39] 36 root - ERROR - Error occurred while reading data from MySQL database
[15-06-2025 23:30:39] 43 root - INFO - Exception occurred in data ingestion
[15-06-2025 23:30:39] 19 root - INFO - CustomException has been raised and caught successfully!
